version: '3.8'
services:
  eureka-server:
    container_name: eureka-server
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - exam-mtgo

networks:
  exam-mtgo: