version: '3.8'
services:
  eureka-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8761:8761"
    networks:
      - order-service-net

networks:
  order-service-net: